# Fast Happy Ghast
# author: wiicart
# wiicart.net

# Default riding speed
# (Vanilla is 0.05)
default-riding-speed: 0.05

# The speed when no player is mounted
idle-speed: 0.01

# Options for the Happy Ghast speed enchantment
enchantment:
  # Name
  name: "velocity"

  # Description
  # (how it will show up on a harness when hovering on it in an inventory)
  description: "Velocity"

  # Weight
  # How common should the enchantment be?
  # Range: 1 - 1024
  weight: 3

  # Enchantment Cost (XP levels)
  cost:
    anvil: 3 # The cost to add the enchantment to a harness with an anvil

    minimum: 1 # The minimum cost for the lowest level
    minimum-modifier: 11 # The amount the minimum goes up by for each enchantment level

    maximum: 15 # The maximum cost for the lowest level
    maximum-modifier: 10 # The amount the maximum goes up for each enchantment level

  # What each level enchantment should set the happy ghast's speed to:
  # Speed Range: 0-1
  levels:
    1: 0.1 # This means enchantment level I gives Happy Ghasts a speed of 0.20
    2: 0.15
    3: 0.17

# Plugin messages
# Uses MiniMessage
# Editor: https://webui.advntr.dev
messages:
  # The prefix before all messages
  prefix: "<dark_gray>[<white>Ghasts</white>]</dark_gray> "

  # Message sent when console issues a command without defining a player
  console-insufficient: "<white>Console must define a player to use this command.</white>"
  # The message sent when a player uses /ghasts givebook
  book-given: "<white>Gave <gray>{quantity}</gray> books to <gray>{player}</gray></white>"
  # Plugin version message
  plugin-version: "<white>Running Ghasts version <green>{version}</green></white>"
  # Reload not supported message
  reload-unsupported: "<white>Reloading is not supported, please restart instead.</white>"
  # Help Message
  help: "<dark_gray>+-------[<white>Ghasts</white>]-------+</dark_gray><newLine>
<white><gray>•</gray> /version - Provides the version<newLine>
<gray>•</gray> /givebook <level> <quantity> <player> - Gives an enchanted book</white>"
  # No Permission
  no-perms: "<red>No permission!</red>"
  # Sent when a player attempts to enchant an invalid item
  invalid-item: "<red>Invalid item, you must be holding a book or harness.</red>"
  # Sent when a player attempts to enchant an item with an invalid enchantment level
  # Placeholder: {max} - the max enchantment level
  invalid-level: "<red>Invalid enchantment level. Must be from 0 to {max}</red>"
  # Sent when a player attempts to run a command with too many args
  too-many-args: "<red>Too many args!</red>"
  # Sent when an item is enchanted with /ghasts enchant
  # Placeholders:
  # {item} - the item that has been enchanted
  # {enchantment} - the enchantment that has been applied
  enchant-success: "<gray>Enchanted {item} with {enchantment}.</gray>"
  # Tells the plugin version
  # Placeholder: {version} - The plugin version
  version: "<light-gray>Running EnchantedHarnesses version <green>{version}</green></light-gray>"
